version: '3.8'

services:
  api:
    container_name: anylangpodpy_api
    build: .
    ports:
      - "5050:5050"
    volumes:
      - type: bind
        source: ./output
        target: /app/output
      - type: bind
        source: ./.env
        target: /app/.env
        read_only: true
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/docs"]
      interval: 30s
      timeout: 10s
      retries: 3 